"""Remove reset token fields

Revision ID: 27960ead01e5
Revises: cde827581dc8
Create Date: 2024-11-12 18:50:37.318925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27960ead01e5'
down_revision = 'cde827581dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
