"""Make sender_wallet_id nullable

Revision ID: 6d40b51d6f8c
Revises: 6975e4c31dd3
Create Date: 2024-11-19 07:49:52.950841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d40b51d6f8c'
down_revision = '6975e4c31dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('sender_wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('sender_wallet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
