"""Add reset_token and reset_token_expiry to User, is_active to Beneficiary, is_reversed to Transaction

Revision ID: db81b37b9cf7
Revises: a820715e99c1
Create Date: 2024-11-11 13:11:59.216532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db81b37b9cf7'
down_revision = 'a820715e99c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reversed', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('is_reversed')

    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
